// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPMghlS2yFKM4uEsUBM5Urc4VGBAKWh4I',
    appId: '1:402037587888:web:622f7a07983cf4773d6075',
    messagingSenderId: '402037587888',
    projectId: 'appclone-2ba2c',
    authDomain: 'appclone-2ba2c.firebaseapp.com',
    storageBucket: 'appclone-2ba2c.appspot.com',
    measurementId: 'G-4CQRWXGDFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv_dyRfrQ-b6_2pi_ZC-fc9vwdUCPOz-k',
    appId: '1:402037587888:android:9983888eb4c492a03d6075',
    messagingSenderId: '402037587888',
    projectId: 'appclone-2ba2c',
    storageBucket: 'appclone-2ba2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgz-vQOmhnhqxtPK884_x32Xwkvh9CaoM',
    appId: '1:402037587888:ios:de7ff5c5a0f9a19a3d6075',
    messagingSenderId: '402037587888',
    projectId: 'appclone-2ba2c',
    storageBucket: 'appclone-2ba2c.appspot.com',
    iosBundleId: 'com.example.diary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgz-vQOmhnhqxtPK884_x32Xwkvh9CaoM',
    appId: '1:402037587888:ios:b3fb1dad7e9502673d6075',
    messagingSenderId: '402037587888',
    projectId: 'appclone-2ba2c',
    storageBucket: 'appclone-2ba2c.appspot.com',
    iosBundleId: 'com.example.diary.RunnerTests',
  );
}
